version: '3.7'

services:
  app:
    container_name: nestjs
    build:
      context: .
      target: development
      # target: production
    image: nestjs
    # image: nestjs-prod
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 9229:9229
    depends_on:
      - mysql
    restart: unless-stopped
  mysql:
    container_name: mysql
    image: mysql:8
    command:
      [
        'mysqld',
        '--character-set-server',
        'utf8mb4',
        '--collation-server',
        'utf8mb4_spanish_ci',
        '--default-authentication-plugin',
        'mysql_native_password',
      ]
    environment:
      MYSQL_DATABASE: ${TYPEORM_DATABASE}
      MYSQL_USER: ${TYPEORM_USERNAME}
      MYSQL_PASSWORD: ${TYPEORM_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${TYPEORM_PASSWORD}
      # TZ: 'America/Argentina/Buenos_Aires'
    networks:
      - webnet
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped

networks:
  webnet:
    name: webnet

volumes:
  mysql-data:
    name: mysql-data
