version: '3.7'

services:
  app:
    container_name: nestjs
    image: manuelnucci/nestjs-dev:1.18.0
    env_file:
      - ./env/development.env
    networks:
      - webnet
    volumes:
      - ./files:/home/node/app/files
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 9229:9229
    depends_on:
      - postgres
    restart: unless-stopped
  postgres:
    container_name: postgres
    build:
      context: ./database
    image: postgres-dev:1.0.0
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    networks:
      - webnet
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped

networks:
  webnet:
    name: webnet

volumes:
  pgdata:
    name: pgdata_dev
