version: '3.7'

services:
  app:
    container_name: sio
    build:
      context: .
      dockerfile: Dockerfile
      # target: build
      target: production
    image: ceiunmdp/sio:0.9.0
    env_file:
      - ./env/beta.env
    networks:
      - webnet
    volumes:
      - ./files:/home/node/app/files
    ports:
      - 443:${APP_PORT}
    depends_on:
      - postgres
    restart: unless-stopped
  postgres:
    container_name: postgres-beta
    build:
      context: ./database
    image: postgres:1.0.0
    env_file:
      - ./env/beta.env
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    networks:
      - webnet
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped

networks:
  webnet:
    name: webnet

volumes:
  pgdata:
    name: pgdata_beta
