version: '3.7'

services:
  app:
    container_name: nestjs
    build:
      context: .
      target: build
      # target: production
    image: nestjs:1.0.0-dev
    # image: nestjs:1.0.0-prod
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 9229:9229
    depends_on:
      # - mysql
      - postgres
    restart: unless-stopped
  # mysql:
  #   container_name: mysql
  #   image: mysql:8.0.21
  #   command:
  #     [
  #       'mysqld',
  #       '--character-set-server',
  #       'utf8mb4',
  #       '--collation-server',
  #       'utf8mb4_spanish_ci',
  #       '--default-authentication-plugin',
  #       'mysql_native_password',
  #     ]
  #   environment:
  #     MYSQL_DATABASE: ${TYPEORM_DATABASE}
  #     MYSQL_USER: ${TYPEORM_USERNAME}
  #     MYSQL_PASSWORD: ${TYPEORM_PASSWORD}
  #     MYSQL_ROOT_PASSWORD: ${TYPEORM_PASSWORD}
  #     # TZ: 'America/Argentina/Buenos_Aires'
  #   networks:
  #     - webnet
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   ports:
  #     - 3306:3306
  #   restart: unless-stopped
  postgres:
    container_name: postgres
    build:
      context: ./database
    image: postgres-es_ar:12.4
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    networks:
      - webnet
    volumes:
      # - mysql-data:/var/lib/mysql
      - pgdata:/var/lib/postgresql/data
    ports:
      # - 3306:3306
      - 5432:5432
    restart: unless-stopped

networks:
  webnet:
    name: webnet

volumes:
  # mysql_data:
  #   name: mysql_data
  pgdata:
    name: pgdata
