version: '3.7'

services:
  # app:
  #   container_name: nestjs
  #   image: manuelnucci/nestjs-dev:1.10.4
  #   env_file:
  #     - .env
  #   networks:
  #     - webnet
  #   volumes:
  #     - ./files:/home/node/app/files
  #     - /var/run/dbus:/var/run/dbus
  #   ports:
  #     - ${APP_PORT}:${APP_PORT}
  #     - 9229:9229
  #   depends_on:
  #     - postgres
  #     # - mysql
  #     # - cups
  #   restart: unless-stopped
  postgres:
    container_name: postgres
    build:
      context: ./database
    image: postgres-dev:1.0.0
    environment:
      POSTGRES_DB: ${TYPEORM_DATABASE}
      POSTGRES_USER: ${TYPEORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    networks:
      - webnet
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped

  # mysql:
  #   container_name: mysql
  #   image: mysql:8.0.21
  #   command:
  #     [
  #       'mysqld',
  #       '--character-set-server',
  #       'utf8mb4',
  #       '--collation-server',
  #       'utf8mb4_spanish_ci',
  #       '--default-authentication-plugin',
  #       'mysql_native_password',
  #     ]
  #   environment:
  #     MYSQL_DATABASE: ${TYPEORM_DATABASE}
  #     MYSQL_USER: ${TYPEORM_USERNAME}
  #     MYSQL_PASSWORD: ${TYPEORM_PASSWORD}
  #     MYSQL_ROOT_PASSWORD: ${TYPEORM_PASSWORD}
  #     # TZ: 'America/Argentina/Buenos_Aires'
  #   networks:
  #     - webnet
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   ports:
  #     - 3306:3306
  #   restart: unless-stopped
  # cups:
  #   container_name: cups
  #   image: ydkn/cups
  #   environment:
  #     ADMIN_PASSWORD: password
  #   networks:
  #     - webnet
  #   volumes:
  #     - cups:/etc/cups
  #   ports:
  #     - 631:631
  #   restart: unless-stopped
  # cups:
  #   container_name: cups
  #   image: lemariva/rpi-cups
  #   privileged: true
  #   volumes:
  #     - /var/run/dbus:/var/run/dbus
  #     - /dev/bus/usb:/dev/bus/usb
  #     - ./printers.conf:/etc/cups/printers.conf
  #   ports:
  #     - 631:631
  #   restart: unless-stopped

networks:
  webnet:
    name: webnet

volumes:
  pgdata:
    name: pgdata_dev
  # mysql_data:
  #   name: mysql_data
  # cups:
  #   name: cups
