-- MySQL Script generated by MySQL Workbench
-- lun 25 may 2020 15:25:40 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema icei
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `icei` ;

-- -----------------------------------------------------
-- Schema icei
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `icei` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci ;
USE `icei` ;

-- -----------------------------------------------------
-- Table `icei`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`roles` ;

CREATE TABLE IF NOT EXISTS `icei`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icei`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`users` ;

CREATE TABLE IF NOT EXISTS `icei`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `salt` VARCHAR(29) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `registered_date` DATETIME NOT NULL,
  `verified_date` DATETIME NULL,
  `verified` TINYINT(1) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  `light_theme` TINYINT(1) NOT NULL,
  `type` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`role_id`)
    REFERENCES `icei`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `email_UNIQUE` ON `icei`.`users` (`email` ASC) VISIBLE;

CREATE INDEX `fk_users_roles_idx` ON `icei`.`users` (`role_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `icei`.`campuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`campuses` ;

CREATE TABLE IF NOT EXISTS `icei`.`campuses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icei`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`orders` ;

CREATE TABLE IF NOT EXISTS `icei`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `campus_id` INT NOT NULL,
  `amount_paid` DECIMAL(6,2) NOT NULL,
  `total` DECIMAL(6,2) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_orders_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `icei`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_campuses`
    FOREIGN KEY (`campus_id`)
    REFERENCES `icei`.`campuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_orders_users_idx` ON `icei`.`orders` (`user_id` ASC) VISIBLE;

CREATE INDEX `fk_orders_campuses_idx` ON `icei`.`orders` (`campus_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `icei`.`states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`states` ;

CREATE TABLE IF NOT EXISTS `icei`.`states` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icei`.`careers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`careers` ;

CREATE TABLE IF NOT EXISTS `icei`.`careers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `code` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icei`.`configurations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`configurations` ;

CREATE TABLE IF NOT EXISTS `icei`.`configurations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `double_sided` TINYINT(1) NOT NULL,
  `slides_per_sheet` SMALLINT NOT NULL,
  `colour` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icei`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`items` ;

CREATE TABLE IF NOT EXISTS `icei`.`items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `price` DECIMAL(6,2) NOT NULL,
  `type` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icei`.`bindings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`bindings` ;

CREATE TABLE IF NOT EXISTS `icei`.`bindings` (
  `id` INT NOT NULL,
  `sheets_limit` SMALLINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_bindings_items`
    FOREIGN KEY (`id`)
    REFERENCES `icei`.`items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_bindings_items_idx` ON `icei`.`bindings` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `icei`.`binding_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`binding_groups` ;

CREATE TABLE IF NOT EXISTS `icei`.`binding_groups` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_binding_groups_bindings`
    FOREIGN KEY (`item_id`)
    REFERENCES `icei`.`bindings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_binding_groups_bindings_idx` ON `icei`.`binding_groups` (`item_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `icei`.`files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`files` ;

CREATE TABLE IF NOT EXISTS `icei`.`files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `extension` VARCHAR(45) NULL,
  `number_of_sheets` SMALLINT NOT NULL,
  `type` TINYINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icei`.`orders_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`orders_files` ;

CREATE TABLE IF NOT EXISTS `icei`.`orders_files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `file_id` INT NOT NULL,
  `state_id` INT NOT NULL,
  `configuration_id` INT NOT NULL,
  `binding_group_id` INT NULL,
  `order` TINYINT NULL,
  `total` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_orders_files_orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `icei`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_files_configurations`
    FOREIGN KEY (`configuration_id`)
    REFERENCES `icei`.`configurations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_files_binding_groups`
    FOREIGN KEY (`binding_group_id`)
    REFERENCES `icei`.`binding_groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_files_files`
    FOREIGN KEY (`file_id`)
    REFERENCES `icei`.`files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_files_states`
    FOREIGN KEY (`state_id`)
    REFERENCES `icei`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_orders_files_orders_idx` ON `icei`.`orders_files` (`order_id` ASC) VISIBLE;

CREATE INDEX `fk_orders_files_configurations_idx` ON `icei`.`orders_files` (`configuration_id` ASC) VISIBLE;

CREATE INDEX `fk_orders_files_binding_groups_idx` ON `icei`.`orders_files` (`binding_group_id` ASC) VISIBLE;

CREATE INDEX `fk_orders_files_states_idx` ON `icei`.`orders_files` (`state_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `icei`.`notification_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`notification_types` ;

CREATE TABLE IF NOT EXISTS `icei`.`notification_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icei`.`notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`notifications` ;

CREATE TABLE IF NOT EXISTS `icei`.`notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `notification_type_id` INT NOT NULL,
  `message` VARCHAR(128) NOT NULL,
  `date` DATETIME NOT NULL,
  `type` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_notifications_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `icei`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notifications_notifications_types`
    FOREIGN KEY (`notification_type_id`)
    REFERENCES `icei`.`notification_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_notifications_users_idx` ON `icei`.`notifications` (`user_id` ASC) VISIBLE;

CREATE INDEX `fk_notifications_notifications_types_idx` ON `icei`.`notifications` (`notification_type_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `icei`.`movement_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`movement_types` ;

CREATE TABLE IF NOT EXISTS `icei`.`movement_types` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '	',
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icei`.`movements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`movements` ;

CREATE TABLE IF NOT EXISTS `icei`.`movements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `source_user_id` INT NOT NULL,
  `taget_user_id` INT NOT NULL,
  `movement_type_id` INT NOT NULL,
  `amount` DECIMAL(6,2) NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_movements_users_1`
    FOREIGN KEY (`source_user_id`)
    REFERENCES `icei`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movements_users_2`
    FOREIGN KEY (`taget_user_id`)
    REFERENCES `icei`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movements_movement_types`
    FOREIGN KEY (`movement_type_id`)
    REFERENCES `icei`.`movement_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_movements_users_1_idx` ON `icei`.`movements` (`source_user_id` ASC) VISIBLE;

CREATE INDEX `fk_movements_users_2_idx` ON `icei`.`movements` (`taget_user_id` ASC) VISIBLE;

CREATE INDEX `fk_movements_movement_types_idx` ON `icei`.`movements` (`movement_type_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `icei`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`courses` ;

CREATE TABLE IF NOT EXISTS `icei`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `code` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `icei`.`careers_courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`careers_courses` ;

CREATE TABLE IF NOT EXISTS `icei`.`careers_courses` (
  `career_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  `relation` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`career_id`, `course_id`),
  CONSTRAINT `fk_careers_courses_careers`
    FOREIGN KEY (`career_id`)
    REFERENCES `icei`.`careers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_careers_courses_courses`
    FOREIGN KEY (`course_id`)
    REFERENCES `icei`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_careers_courses_careers_idx` ON `icei`.`careers_courses` (`career_id` ASC) VISIBLE;

CREATE INDEX `fk_careers_courses_courses_idx` ON `icei`.`careers_courses` (`course_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `icei`.`system_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`system_files` ;

CREATE TABLE IF NOT EXISTS `icei`.`system_files` (
  `file_id` INT NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`file_id`, `course_id`),
  CONSTRAINT `fk_system_files_files`
    FOREIGN KEY (`file_id`)
    REFERENCES `icei`.`files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_system_files_courses`
    FOREIGN KEY (`course_id`)
    REFERENCES `icei`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_system_files_files_idx` ON `icei`.`system_files` (`file_id` ASC) VISIBLE;

CREATE INDEX `fk_system_files_courses_idx` ON `icei`.`system_files` (`course_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `icei`.`uploaded_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`uploaded_files` ;

CREATE TABLE IF NOT EXISTS `icei`.`uploaded_files` (
  `file_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`file_id`, `user_id`),
  CONSTRAINT `fk_uploaded_files_files`
    FOREIGN KEY (`file_id`)
    REFERENCES `icei`.`files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uploaded_files_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `icei`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_uploaded_files_files_idx` ON `icei`.`uploaded_files` (`file_id` ASC) VISIBLE;

CREATE INDEX `fk_uploaded_files_users_idx` ON `icei`.`uploaded_files` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `icei`.`campus_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`campus_users` ;

CREATE TABLE IF NOT EXISTS `icei`.`campus_users` (
  `id` INT NOT NULL,
  `campus_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_campus_users_users`
    FOREIGN KEY (`id`)
    REFERENCES `icei`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_campus_users_campuses`
    FOREIGN KEY (`campus_id`)
    REFERENCES `icei`.`campuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_campus_users_users_idx` ON `icei`.`campus_users` (`id` ASC) VISIBLE;

CREATE INDEX `fk_campus_users_campuses_idx` ON `icei`.`campus_users` (`campus_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `icei`.`students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`students` ;

CREATE TABLE IF NOT EXISTS `icei`.`students` (
  `id` INT NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `surname` VARCHAR(64) NOT NULL,
  `dni` VARCHAR(24) NOT NULL,
  `balance` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_students_users`
    FOREIGN KEY (`id`)
    REFERENCES `icei`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_students_users_idx` ON `icei`.`students` (`id` ASC) VISIBLE;

CREATE UNIQUE INDEX `dni_UNIQUE` ON `icei`.`students` (`dni` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `icei`.`professorships`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`professorships` ;

CREATE TABLE IF NOT EXISTS `icei`.`professorships` (
  `id` INT NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_professorships_courses`
    FOREIGN KEY (`course_id`)
    REFERENCES `icei`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professorships_users`
    FOREIGN KEY (`id`)
    REFERENCES `icei`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_professorships_courses_idx` ON `icei`.`professorships` (`course_id` ASC) VISIBLE;

CREATE INDEX `fk_professorships_users_idx` ON `icei`.`professorships` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `icei`.`scholarship_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`scholarship_list` ;

CREATE TABLE IF NOT EXISTS `icei`.`scholarship_list` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(24) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `surname` VARCHAR(64) NOT NULL,
  `available_copies` SMALLINT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `dni_UNIQUE` ON `icei`.`scholarship_list` (`dni` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `icei`.`scholarship_students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`scholarship_students` ;

CREATE TABLE IF NOT EXISTS `icei`.`scholarship_students` (
  `id` INT NOT NULL,
  `scholarshipListId` INT NOT NULL,
  `available_copies` SMALLINT NOT NULL,
  `remaining_copies` SMALLINT NOT NULL,
  `verified` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_scholarship_students_scholarship_list`
    FOREIGN KEY (`scholarshipListId`)
    REFERENCES `icei`.`scholarship_list` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_scholarship_students_students`
    FOREIGN KEY (`id`)
    REFERENCES `icei`.`students` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_scholarship_students_scholarship_list_idx` ON `icei`.`scholarship_students` (`scholarshipListId` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `icei`.`admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`admins` ;

CREATE TABLE IF NOT EXISTS `icei`.`admins` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_admins_users`
    FOREIGN KEY (`id`)
    REFERENCES `icei`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_admins_users_idx` ON `icei`.`admins` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `icei`.`orders_states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`orders_states` ;

CREATE TABLE IF NOT EXISTS `icei`.`orders_states` (
  `order_id` INT NOT NULL,
  `state_id` INT NOT NULL,
  `date` DATETIME NOT NULL,
  PRIMARY KEY (`order_id`, `state_id`),
  CONSTRAINT `fk_order_states_orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `icei`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_estado_estado1`
    FOREIGN KEY (`state_id`)
    REFERENCES `icei`.`states` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_order_states_orders_idx` ON `icei`.`orders_states` (`state_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `icei`.`physical_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`physical_files` ;

CREATE TABLE IF NOT EXISTS `icei`.`physical_files` (
  `file_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`file_id`, `user_id`),
  CONSTRAINT `fk_physical_files_files`
    FOREIGN KEY (`file_id`)
    REFERENCES `icei`.`files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_physical_files_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `icei`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_physical_files_users_idx` ON `icei`.`physical_files` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `icei`.`notification_requests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`notification_requests` ;

CREATE TABLE IF NOT EXISTS `icei`.`notification_requests` (
  `notification_id` INT NOT NULL,
  `order_id` INT NOT NULL,
  PRIMARY KEY (`notification_id`),
  CONSTRAINT `fk_notification_requests_notifications`
    FOREIGN KEY (`notification_id`)
    REFERENCES `icei`.`notifications` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notification_requests_orders`
    FOREIGN KEY (`order_id`)
    REFERENCES `icei`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_notification_requests_orders_idx` ON `icei`.`notification_requests` (`order_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `icei`.`modules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`modules` ;

CREATE TABLE IF NOT EXISTS `icei`.`modules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `module_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_modules_modules`
    FOREIGN KEY (`module_id`)
    REFERENCES `icei`.`modules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_modules_modules_idx` ON `icei`.`modules` (`module_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `icei`.`functionalities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`functionalities` ;

CREATE TABLE IF NOT EXISTS `icei`.`functionalities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(25) NOT NULL,
  `module_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_functionalities_modules`
    FOREIGN KEY (`module_id`)
    REFERENCES `icei`.`modules` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_functionalities_modules_idx` ON `icei`.`functionalities` (`module_id` ASC) VISIBLE;

CREATE UNIQUE INDEX `ruta_UNIQUE` ON `icei`.`functionalities` (`code` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `icei`.`functionalities_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `icei`.`functionalities_roles` ;

CREATE TABLE IF NOT EXISTS `icei`.`functionalities_roles` (
  `functionality_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`functionality_id`, `role_id`),
  CONSTRAINT `fk_functionalities_roles_functionalities`
    FOREIGN KEY (`functionality_id`)
    REFERENCES `icei`.`functionalities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_functionalities_roles_roles`
    FOREIGN KEY (`role_id`)
    REFERENCES `icei`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_functionalities_roles_roles` ON `icei`.`functionalities_roles` (`role_id` ASC) VISIBLE;

CREATE INDEX `fk_functionalities_roles_functionalities_idx` ON `icei`.`functionalities_roles` (`functionality_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
