export enum EFunctionality {
  MENU = 'menu',
  CAMPUSES = 'campuses',
  HOME = 'home',
  ORDERS = 'orders',
  MOVEMENTS = 'movements',
  OPERATIONS = 'operations',

  NEW_ORDER = 'new_order',
  MY_ORDERS = 'my_orders',
  MY_MOVEMENTS = 'my_movements',
  USERS = 'users',
  CAREERS = 'careers',
  COURSES = 'courses',
  FILES = 'files',
  ITEMS = 'items',
  BINDINGS = 'bindings',
  PARAMETERS = 'parameters',
  TOP_UP = 'top_up',
  TRANSFER_MONEY = 'transfer_money',
}
