version: '3.7'

services:
  # wireguard:
  #   container_name: wireguard
  #   image: linuxserver/wireguard:version-v1.0.20200827
  #   cap_add:
  #     - NET_ADMIN
  #     - SYS_MODULE
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Argentina/Buenos_Aires
  #     - SERVERURL=34.69.93.181 #optional
  #     - SERVERPORT=51820 #optional
  #     - PEERS=raspberrypi,manuelnucci #optional
  #     - PEERDNS=auto #optional
  #     - INTERNAL_SUBNET=10.13.13.0 #optional
  #     - ALLOWEDIPS=0.0.0.0/0 #optional
  #   networks:
  #     - web
  #   ports:
  #     - 51820:51820/udp
  #     - 80:${APP_PORT} # NestJS
  #     # - 5432:5432 # Postgres
  #   volumes:
  #     - /lib/modules:/lib/modules
  #     - ./wireguard/config:/config
  #   sysctls:
  #     - net.ipv4.conf.all.src_valid_mark=1
  #   restart: unless-stopped

  openvpn:
    container_name: openvpn
    image: kylemanna/openvpn:2.4
    cap_add:
      - NET_ADMIN
    networks:
      - web
    ports:
      - 1194:1194/udp
    volumes:
      - ./openvpn-data/conf:/etc/openvpn
    restart: unless-stopped

  # mdns:
  #   container_name: mdns
  #   image: manuelnucci/mdns
  #   network_mode: service:openvpn
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup
  #     - /var/run/dbus:/var/run/dbus
  #     - ./files:/home/node/app/files
  #   depends_on:
  #     - wireguard
  #   restart: unless-stopped

networks:
  web:
    name: web
    driver: bridge
