name: Build and publish Docker image
on:
  push: # every pull request is followed by a push
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Read version from package.json
        uses: nyaayaya/package-version@v1

      - name: Decrypt all managed filespostdeploy
        uses: jrmcdonald/blackbox-github-actions@v0.2.0
        with:
          bb_actions_subcommand: 'postdeploy'
        env:
          BLACKBOX_PUBKEY: ${{ secrets.BLACKBOX_PUBKEY }}
          BLACKBOX_PRIVKEY: ${{ secrets.BLACKBOX_PRIVKEY }}

      - name: Publish to Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: manuelnucci/nestjs-dev
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          default_branch: develop
          dockerfile: Dockerfile.dev
          cache: true
          tags: 'latest,${{ env.PACKAGE_VERSION }}'

      - name: Safely delete any decrypted files
        uses: jrmcdonald/blackbox-github-actions@v0.2.0
        with:
          bb_actions_subcommand: 'shred_all_files'
        env:
          BLACKBOX_PUBKEY: ${{ secrets.BLACKBOX_PUBKEY }}
          BLACKBOX_PRIVKEY: ${{ secrets.BLACKBOX_PRIVKEY }}
